runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: cssz

- url: /admin
  login: admin
  script: main.app
  auth_fail_action: unauthorized

- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.xml$
- ^(.*/)?\.txt$
- .+\.xml

error_handlers:
  - file: templates/default_error.html
  
  # [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: japanese2-166714:europe-west1:japanese
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: japanesejim
    CLOUDSQL_DATABASE: japanese
# [END env_variables]
