runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /html
  static_dir: html

- url: /css
  static_dir: css

- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.xml$
- ^(.*/)?\.txt$
- .+\.xml

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: japanese2-166714:europe-west1:japanese
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: japanesejim
    CLOUDSQL_DATABASE: japanese
# [END env_variables]
